# Generated by Django 5.2.7 on 2025-10-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('ogrenci_no', models.CharField(max_length=20, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('kullanici_adi', models.CharField(max_length=50, unique=True)),
                ('sifre_hash', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('personel', 'Personel')], default='personel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yayin_yili', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kutuphane_app.kategori')),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kutuphane_app.yazar')),
            ],
        ),
        migrations.CreateModel(
            name='KitapNusha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod', models.CharField(max_length=50, unique=True)),
                ('durum', models.CharField(choices=[('mevcut', 'Mevcut'), ('oduncte', 'Ödünçte'), ('kayip', 'Kayıp')], default='mevcut', max_length=20)),
                ('raf_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nushalar', to='kutuphane_app.kitap')),
            ],
        ),
        migrations.CreateModel(
            name='OduncKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odunc_tarihi', models.DateTimeField(auto_now_add=True)),
                ('iade_tarihi', models.DateTimeField()),
                ('teslim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('oduncte', 'Ödünçte'), ('teslim', 'Teslim Edildi')], default='oduncte', max_length=20)),
                ('gecikme_cezasi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kitap_nusha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutuphane_app.kitapnusha')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutuphane_app.ogrenci')),
            ],
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sinif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kutuphane_app.sinif'),
        ),
    ]
