# Generated by Django 5.2.7 on 2025-10-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
                ('odunc_suresi_gun', models.IntegerField(default=15)),
                ('maksimum_kitap', models.IntegerField(default=3)),
                ('gecikme_ceza_gunluk', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kutuphane_app.rol'),
        ),
    ]
