# Generated by Django 5.2.7 on 2025-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0002_rol_ogrenci_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
