# Generated by Django 5.2.7 on 2025-10-02 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0003_alter_ogrenci_kayit_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
