# Generated by Django 5.2.7 on 2025-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0004_alter_ogrenci_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
