# Generated by Django 5.2.7 on 2025-10-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0005_ogrenci_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArsivBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(blank=True, max_length=200)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('json_dosya', models.FileField(blank=True, null=True, upload_to='arsiv/')),
            ],
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='pasif_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArsivOdunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_no', models.CharField(max_length=20)),
                ('kitap_baslik', models.CharField(max_length=200)),
                ('barkod', models.CharField(max_length=50)),
                ('odunc_tarihi', models.DateTimeField()),
                ('iade_tarihi', models.DateTimeField()),
                ('teslim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(max_length=20)),
                ('gecikme_cezasi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsiv_oduncler', to='kutuphane_app.arsivbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ArsivOgrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_no', models.CharField(max_length=20)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('sinif_ad', models.CharField(blank=True, max_length=20, null=True)),
                ('rol_ad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True)),
                ('kayit_tarihi', models.DateTimeField(blank=True, null=True)),
                ('pasif_tarihi', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsiv_ogrenciler', to='kutuphane_app.arsivbatch')),
            ],
        ),
    ]
