# Generated by Django 5.2.7 on 2025-10-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0006_arsivbatch_ogrenci_pasif_tarihi_arsivodunc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'managed': False,
            },
        ),
    ]
