# Generated by Django 5.2.7 on 2025-10-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0007_systemsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
