# Generated by Django 5.2.7 on 2025-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0008_delete_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitapnusha',
            name='durum',
            field=models.CharField(choices=[('mevcut', 'Mevcut'), ('oduncte', 'Ödünçte'), ('kayip', 'Kayıp'), ('hasarli', 'Hasarlı')], default='mevcut', max_length=20),
        ),
        migrations.AlterField(
            model_name='odunckaydi',
            name='durum',
            field=models.CharField(choices=[('oduncte', 'Ödünçte'), ('teslim', 'Teslim Edildi'), ('gecikmis', 'Gecikmiş'), ('kayip', 'Kayıp'), ('hasarli', 'Hasarlı'), ('iptal', 'İptal')], default='oduncte', max_length=20),
        ),
    ]
