# Generated by Django 5.2.7 on 2026-09-18 22:32

import django.core.validators
import kutuphane_app.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0024_trigram_title_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_password',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_username',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_api_key',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='eposta',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='telefon',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
    ]
