# Generated by Django 5.2.7 on 2026-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0027_arama_search_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpolicy',
            name='kayip_hasar_cezasi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kayıp/hasarlı nüsha için önerilen ek ceza tutarı (TL). Sıfırsa öneri üretilmez.', max_digits=8),
        ),
    ]
