# Generated by Django 5.2.7 on 2026-09-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0028_loanpolicy_kayip_hasar_cezasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
                ('aciklama', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('ad',),
            },
        ),
        migrations.AddField(
            model_name='kitap',
            name='kapak_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kitapnusha',
            name='raf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nushalar', to='kutuphane_app.raf'),
        ),
    ]
