# Generated by Django 5.2.7 on 2026-09-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0030_link_existing_raf_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='parola_degistirilsin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci', to=settings.AUTH_USER_MODEL),
        ),
    ]
