# Generated by Django 5.2.7 on 2026-09-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0034_upper_uye_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurumAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=50, unique=True)),
                ('kutuphane_adi', models.CharField(blank=True, max_length=150)),
                ('okul_adi', models.CharField(blank=True, max_length=150)),
                ('adres', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=40)),
                ('eposta', models.CharField(blank=True, max_length=120)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurum Bilgileri',
                'verbose_name_plural': 'Kurum Bilgileri',
            },
        ),
    ]
