# Generated by Django 5.2.7 on 2026-09-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0035_kurumayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='odunckaydi',
            name='kapanis_notu',
            field=models.TextField(blank=True, default=''),
        ),
    ]
