# Generated by Django 5.2.7 on 2026-09-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0036_odunckaydi_kapanis_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Öğretmen görüşü: kitap hakkında uzman değerlendirmesi; üye inceleme ekranında gösterilir.'),
        ),
    ]
