# Generated by Django 5.2.7 on 2026-09-25 17:10

import datetime
import django.db.models.deletion
import kutuphane_app.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0037_alter_kitap_aciklama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roller'},
        ),
        migrations.AlterModelOptions(
            name='roleloanpolicy',
            options={'verbose_name': 'Rol Ödünç Kuralı', 'verbose_name_plural': 'Rol Ödünç Kuralları'},
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='adres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='eposta',
            field=models.CharField(blank=True, max_length=120, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='kutuphane_adi',
            field=models.CharField(blank=True, help_text='Fiş ve etiketlerde görünen kütüphane adı.', max_length=150, verbose_name='Kütüphane adı'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Fiş/etiketlerde kullanılacak logo görselinin açık adresi.', max_length=500, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='okul_adi',
            field=models.CharField(blank=True, max_length=150, verbose_name='Okul adı'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AlterField(
            model_name='kurumayarlari',
            name='website',
            field=models.CharField(blank=True, max_length=150, verbose_name='Web sitesi'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='auto_extend_days',
            field=models.PositiveIntegerField(default=0, help_text='Otomatik uzatmada iade tarihinin kaç gün öteleneceği.', verbose_name='Otomatik uzatma süresi (gün)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='auto_extend_enabled',
            field=models.BooleanField(default=False, help_text='Süre dolarken ödünç otomatik uzatılır (aşağıdaki gün/limit kullanılır).', verbose_name='Otomatik uzatma açık'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='auto_extend_limit',
            field=models.PositiveIntegerField(default=0, help_text='Bir ödünç kaydının en fazla kaç kez uzatılabileceği.', verbose_name='Otomatik uzatma limiti (kez)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='default_duration',
            field=models.PositiveIntegerField(default=15, help_text='Rol için özel değer tanımlı değilse kitabın kaç gün ödünç verileceği.', verbose_name='Varsayılan ödünç süresi (gün)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='default_max_items',
            field=models.PositiveIntegerField(default=2, help_text='Rol için özel değer yoksa bir üyenin aynı anda alabileceği kitap sayısı.', verbose_name='Varsayılan en fazla kitap'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='delay_grace_days',
            field=models.PositiveIntegerField(default=0, help_text='Bu kadar gün gecikme cezasız kabul edilir.', verbose_name='Varsayılan iade toleransı (gün)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='kayip_hasar_cezasi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kayıp/hasarlı nüsha için önerilen ek ceza tutarı (TL). Sıfırsa öneri üretilmez.', max_digits=8, verbose_name='Kayıp/hasarlı cezası (₺)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='penalty_delay_days',
            field=models.PositiveIntegerField(default=0, help_text='Toleranstan sonra cezanın başlaması için geçen ek gün.', verbose_name='Varsayılan ceza gecikmesi (gün)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='penalty_max_per_loan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tek ödünç kaydı için en yüksek ceza (0 = sınırsız).', max_digits=8, verbose_name='Ceza tavanı – kitap (₺)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='penalty_max_per_student',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bir üyenin toplam cezasının üst sınırı (0 = sınırsız).', max_digits=8, verbose_name='Ceza tavanı – üye (₺)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='quarantine_days',
            field=models.PositiveIntegerField(default=0, help_text='İade edilen nüshanın yeniden ödünç verilebilmesi için beklenecek gün.', verbose_name='Karantina (gün)'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='Belirtilen aralıkta bildirim gönderimi ertelenir.', verbose_name='Sessiz saatler açık'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Bitiş; başlangıçtan küçükse gece yarısını aşar (ör. 22:00–08:00).', verbose_name='Sessiz saat bitişi'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Sessiz aralığın başlangıcı (SS:DD).', verbose_name='Sessiz saat başlangıcı'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='require_damage_note',
            field=models.BooleanField(default=False, help_text='Kayıp/hasarlı iade kapatılırken açıklama girilmesi zorunlu olur.', verbose_name='Hasarlı iade için not zorunlu'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='require_shelf_code',
            field=models.BooleanField(default=False, help_text='Yeni nüsha eklerken raf seçilmesi zorunlu olur.', verbose_name='Raf kodu zorunlu'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='shift_weekend',
            field=models.BooleanField(default=False, help_text='İade tarihi hafta sonuna denk gelirse sonraki iş gününe kaydırılır.', verbose_name='Hafta sonu kaydır'),
        ),
        migrations.AlterField(
            model_name='loanpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_overdue_days_after',
            field=models.PositiveIntegerField(default=0, help_text='İade tarihi geçtikten kaç gün sonra bildirim gönderileceği.', verbose_name='Gecikmeden kaç gün sonra'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_overdue_enabled',
            field=models.BooleanField(default=True, help_text='İade tarihi geçen üyelere gecikme bildirimi gönderilir.', verbose_name='Gecikme bildirimi açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_reminder_days_before',
            field=models.PositiveIntegerField(default=1, help_text='İade tarihinden kaç gün önce hatırlatma yapılacağı.', verbose_name='Kaç gün önce hatırlat'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_reminder_email_enabled',
            field=models.BooleanField(default=True, verbose_name='Hatırlatma – e-posta'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_reminder_enabled',
            field=models.BooleanField(default=True, help_text='İade tarihi yaklaşan üyelere hatırlatma gönderilir.', verbose_name='İade hatırlatma açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_reminder_mobile_enabled',
            field=models.BooleanField(default=True, verbose_name='Hatırlatma – mobil'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='due_reminder_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='Hatırlatma – SMS'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='E-posta gönderimi açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_password',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512, verbose_name='SMTP şifre'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='E-posta zamanlama açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_schedule_hour',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='E-posta saat'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_schedule_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-posta son çalışma'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_schedule_minute',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='E-posta dakika'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_schedule_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='E-posta saat dilimi'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_sender',
            field=models.CharField(blank=True, max_length=120, verbose_name='Gönderen adresi'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_smtp_host',
            field=models.CharField(blank=True, max_length=120, verbose_name='SMTP sunucu'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP portu'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS kullan'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_username',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512, verbose_name='SMTP kullanıcı'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_enabled',
            field=models.BooleanField(default=False, verbose_name='Mobil bildirim açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='Mobil zamanlama açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_schedule_hour',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Mobil saat'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_schedule_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mobil son çalışma'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_schedule_minute',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mobil dakika'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='mobile_schedule_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mobil saat dilimi'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_body',
            field=models.TextField(blank=True, verbose_name='Gecikme metni'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_email_enabled',
            field=models.BooleanField(default=True, verbose_name='Gecikme – e-posta'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_last_run',
            field=models.DateField(blank=True, null=True, verbose_name='Gecikme son çalışma'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_mobile_enabled',
            field=models.BooleanField(default=True, verbose_name='Gecikme – mobil'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='Gecikme – SMS'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='overdue_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gecikme konusu'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='printer_warning_enabled',
            field=models.BooleanField(default=True, help_text='Uygulama açılışında yazıcı sorunu varsa uyarı gösterilir.', verbose_name='Açılışta yazıcı uyarısı'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='reminder_body',
            field=models.TextField(blank=True, verbose_name='Hatırlatma metni'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='reminder_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hatırlatma konusu'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_api_key',
            field=kutuphane_app.encryption.EncryptedCharField(blank=True, max_length=512, verbose_name='SMS API anahtarı'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_api_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMS API URL'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='SMS gönderimi açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_provider',
            field=models.CharField(blank=True, max_length=120, verbose_name='SMS sağlayıcı'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='SMS zamanlama açık'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_schedule_hour',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='SMS saat'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_schedule_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SMS son çalışma'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_schedule_minute',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='SMS dakika'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_schedule_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='SMS saat dilimi'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ad',
            field=models.CharField(help_text='Öğrenci, Öğretmen, Editör gibi rol adı.', max_length=50, unique=True, verbose_name='Rol adı'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='daily_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gecikme başladıktan sonra her gün için uygulanan tutar (0 = ceza yok).', max_digits=6, verbose_name='Günlük ceza (₺)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='delay_grace_days',
            field=models.PositiveIntegerField(blank=True, help_text='Ceza başlamadan önce tanınan ek gün. Boşsa genel değer.', null=True, verbose_name='İade toleransı (gün)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Kitabın kaç gün ödünç verileceği. Boşsa genel Ödünç Politikası değeri kullanılır.', null=True, verbose_name='Ödünç süresi (gün)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='max_items',
            field=models.PositiveIntegerField(blank=True, help_text='Bu roldeki bir üyenin aynı anda alabileceği kitap sayısı. Boşsa genel değer.', null=True, verbose_name='En fazla kitap'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='penalty_delay_days',
            field=models.PositiveIntegerField(blank=True, help_text='Toleranstan sonra cezanın başlaması için geçen ek gün. Boşsa genel değer.', null=True, verbose_name='Ceza gecikmesi (gün)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='penalty_max_per_loan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tek ödünç kaydı için en yüksek ceza (0 = sınırsız). Boşsa genel değer.', max_digits=8, null=True, verbose_name='Ceza tavanı – kitap (₺)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='penalty_max_per_student',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bir üyenin toplam cezasının üst sınırı (0 = sınırsız). Boşsa genel değer.', max_digits=8, null=True, verbose_name='Ceza tavanı – üye (₺)'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='role',
            field=models.OneToOneField(help_text='Bu ödünç kurallarının geçerli olduğu rol.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_policy', to='kutuphane_app.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='roleloanpolicy',
            name='shift_weekend',
            field=models.BooleanField(blank=True, help_text='İade tarihi hafta sonuna denk gelirse sonraki iş gününe kaydırılır.', null=True, verbose_name='Hafta sonu kaydır'),
        ),
    ]
