# Generated by Django 5.2.7 on 2026-10-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane_app', '0038_alter_rol_options_alter_roleloanpolicy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CihazBildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True, verbose_name='FCM token')),
                ('platform', models.CharField(default='android', max_length=20, verbose_name='Platform')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirim_cihazlari', to='kutuphane_app.uye', verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Bildirim Cihazı',
                'verbose_name_plural': 'Bildirim Cihazları',
            },
        ),
    ]
